-- MySQL Script generated by MySQL Workbench
-- Wed Aug 11 11:09:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`fund_managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fund_managers` (
  `employee_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funds` (
  `fund_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `fund_manager_employee_id` INT NOT NULL,
  PRIMARY KEY (`fund_id`, `fund_manager_employee_id`),
  INDEX `fk_funds_fund_manager_idx` (`fund_manager_employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_funds_fund_manager`
    FOREIGN KEY (`fund_manager_employee_id`)
    REFERENCES `mydb`.`fund_managers` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Securites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Securites` (
  `security_id` INT NOT NULL,
  `Symbol` VARCHAR(45) NULL,
  PRIMARY KEY (`security_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Positions` (
  `position_id` INT NOT NULL,
  `security_id` INT NULL,
  `quantity` INT NULL,
  `Date_purchased` DATE NULL,
  `funds_fund_id` INT NOT NULL,
  `funds_fund_manager_employee_id` INT NOT NULL,
  `Securites_security_id` INT NOT NULL,
  PRIMARY KEY (`position_id`, `funds_fund_id`, `funds_fund_manager_employee_id`, `Securites_security_id`),
  INDEX `fk_Positions_funds1_idx` (`funds_fund_id` ASC, `funds_fund_manager_employee_id` ASC) VISIBLE,
  INDEX `fk_Positions_Securites1_idx` (`Securites_security_id` ASC) VISIBLE,
  CONSTRAINT `fk_Positions_funds1`
    FOREIGN KEY (`funds_fund_id` , `funds_fund_manager_employee_id`)
    REFERENCES `mydb`.`funds` (`fund_id` , `fund_manager_employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Positions_Securites1`
    FOREIGN KEY (`Securites_security_id`)
    REFERENCES `mydb`.`Securites` (`security_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
